'use client';

import React, { useMemo } from 'react';
import { HugeiconsIcon } from '@hugeicons/react';
import {
  CopyIcon,
  CheckmarkCircle01Icon,
  Download01Icon,
  FolderZipIcon,
} from '@hugeicons/core-free-icons';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { useFlowStore } from '@/lib/useFlowStore';
import JSZip from 'jszip';

interface CodeExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  code: string;
}

function generatePackageJson(name: string): string {
  const safeName =
    name
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '') || 'mcp-flow-server';

  return JSON.stringify(
    {
      name: safeName,
      version: '1.0.0',
      type: 'module',
      scripts: {
        dev: 'mcp-use dev',
        build: 'mcp-use build',
        start: 'node dist/index.js',
      },
      dependencies: {
        'mcp-use': 'latest',
        zod: '^3.23.0',
      },
      devDependencies: {
        typescript: '^5.0.0',
      },
    },
    null,
    2,
  );
}

const TSCONFIG = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      module: 'ES2022',
      moduleResolution: 'bundler',
      esModuleInterop: true,
      strict: true,
      skipLibCheck: true,
      outDir: './dist',
      rootDir: '.',
      declaration: true,
    },
    include: ['index.ts'],
    exclude: ['node_modules', 'dist'],
  },
  null,
  2,
);

function generateEnvExample(code: string): string {
  const envVars: string[] = [];
  const regex = /process\.env\["([^"]+)"\]/g;
  let match;
  while ((match = regex.exec(code)) !== null) {
    if (!envVars.includes(match[1])) {
      envVars.push(match[1]);
    }
  }

  if (envVars.length === 0) {
    return '# No environment variables required\nPORT=3000\n';
  }

  return ['PORT=3000', '', ...envVars.map((v) => `${v}=`), ''].join('\n');
}

function generateReadme(name: string): string {
  return `# ${name}

MCP Server generated by [MCP-Flow](https://github.com/udaykumar-dhokia/mcp-flow).

## Setup

\`\`\`bash
npm install
\`\`\`

## Development

\`\`\`bash
npm run dev
\`\`\`

The server starts at \`http://localhost:3000/mcp\` with the inspector at \`http://localhost:3000/inspector\`.

## Production

\`\`\`bash
npm run build
npm start
\`\`\`

## Connect to AI Clients

Add this server URL to your MCP-compatible client:

- **Claude Desktop**: Add to \`claude_desktop_config.json\`
- **Cursor**: Add to MCP server settings
- **ChatGPT**: Use with MCP Apps

\`\`\`
http://localhost:3000/mcp
\`\`\`
`;
}

interface FileTab {
  id: string;
  label: string;
  filename: string;
  content: string;
}

export default function CodeExportModal({ isOpen, onClose, code }: CodeExportModalProps) {
  const [copiedTab, setCopiedTab] = React.useState<string | null>(null);
  const workflowName = useFlowStore((s) => s.workflowName);

  const files: FileTab[] = useMemo(
    () => [
      { id: 'server', label: 'index.ts', filename: 'index.ts', content: code },
      {
        id: 'package',
        label: 'package.json',
        filename: 'package.json',
        content: generatePackageJson(workflowName),
      },
      { id: 'tsconfig', label: 'tsconfig.json', filename: 'tsconfig.json', content: TSCONFIG },
      {
        id: 'env',
        label: '.env.example',
        filename: '.env.example',
        content: generateEnvExample(code),
      },
      {
        id: 'readme',
        label: 'README.md',
        filename: 'README.md',
        content: generateReadme(workflowName),
      },
    ],
    [code, workflowName],
  );

  const copyToClipboard = (tabId: string, text: string) => {
    void navigator.clipboard.writeText(text);
    setCopiedTab(tabId);
    setTimeout(() => setCopiedTab(null), 2000);
  };

  const downloadFile = (content: string, filename: string) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadAllAsZip = async () => {
    const zip = new JSZip();
    files.forEach((file) => {
      zip.file(file.filename, file.content);
    });

    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${workflowName.toLowerCase().replace(/\s+/g, '-')}-mcp-server.zip`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-4xl overflow-hidden border-zinc-200 p-0 dark:border-zinc-800 dark:bg-zinc-950">
        <DialogHeader className="flex flex-row items-center justify-between gap-3 border-b border-zinc-100 px-5 py-4 dark:border-zinc-800">
          <div className="flex flex-col gap-0.5">
            <DialogTitle className="text-sm font-semibold">Generated MCP Server</DialogTitle>
            <DialogDescription className="text-[10px] text-zinc-500">
              Download or copy your server code
            </DialogDescription>
          </div>
          <Button
            variant="outline"
            size="sm"
            className="gap-1.5 text-xs"
            onClick={() => void downloadAllAsZip()}
          >
            <HugeiconsIcon icon={FolderZipIcon} size={14} />
            Download ZIP
          </Button>
        </DialogHeader>

        <Tabs defaultValue="server" className="flex flex-col">
          <TabsList className="mx-5 mt-4 grid w-auto grid-cols-5 bg-zinc-100/50 p-1 dark:bg-zinc-900/50">
            {files.map((file) => (
              <TabsTrigger
                key={file.id}
                value={file.id}
                className="text-[11px] data-[state=active]:bg-white data-[state=active]:shadow-sm dark:data-[state=active]:bg-zinc-800"
              >
                {file.label}
              </TabsTrigger>
            ))}
          </TabsList>

          {files.map((file) => (
            <TabsContent key={file.id} value={file.id} className="px-5 pb-5">
              <div className="mb-3 flex justify-end gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  className="h-8 gap-1.5 text-[11px] font-medium"
                  onClick={() => copyToClipboard(file.id, file.content)}
                >
                  {copiedTab === file.id ? (
                    <HugeiconsIcon
                      icon={CheckmarkCircle01Icon}
                      size={14}
                      className="text-emerald-500"
                    />
                  ) : (
                    <HugeiconsIcon icon={CopyIcon} size={14} />
                  )}
                  {copiedTab === file.id ? 'Copied' : 'Copy'}
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  className="h-8 gap-1.5 text-[11px] font-medium"
                  onClick={() => downloadFile(file.content, file.filename)}
                >
                  <HugeiconsIcon icon={Download01Icon} size={14} />
                  Download
                </Button>
              </div>
              <div className="max-h-[50vh] overflow-y-auto rounded-lg bg-zinc-50 p-4 dark:bg-zinc-900">
                <pre className="font-mono text-[11px] leading-relaxed text-zinc-600 dark:text-zinc-400">
                  {file.content}
                </pre>
              </div>
            </TabsContent>
          ))}
        </Tabs>

        <div className="border-t border-zinc-100 bg-zinc-50/50 px-5 py-4 dark:border-zinc-800 dark:bg-zinc-900/50">
          <h4 className="mb-1.5 text-[10px] font-bold tracking-wider text-zinc-500 uppercase">
            Quick Start
          </h4>
          <ol className="list-decimal space-y-1 pl-4 text-[11px] text-zinc-500">
            <li>Download the ZIP and extract to a new directory</li>
            <li>
              Copy <code className="font-mono text-zinc-700 dark:text-zinc-300">.env.example</code>{' '}
              to <code className="font-mono text-zinc-700 dark:text-zinc-300">.env</code> and fill
              in your secrets
            </li>
            <li>
              Run <code className="font-mono text-zinc-700 dark:text-zinc-300">npm install</code>
            </li>
            <li>
              Run <code className="font-mono text-zinc-700 dark:text-zinc-300">npm run dev</code>
            </li>
            <li>Add the server URL to Claude, Cursor, or ChatGPT</li>
          </ol>
        </div>
      </DialogContent>
    </Dialog>
  );
}
