import { Injectable } from '@nestjs/common';

import {
  Graph,
  GraphNode,
  GraphEdge,
  NodeParameter,
  TransformMapping,
} from './dto/graph.dto';

@Injectable()
export class GeneratorService {
  generate(graph: Graph): string {
    const { nodes, edges } = graph;

    const inputNodes = nodes.filter((n) => n.type === 'inputNode');
    const outputNodes = nodes.filter((n) => n.type === 'outputNode');

    if (inputNodes.length === 0) {
      return '// Error: No Input node found. Add at least one Input node.';
    }
    if (outputNodes.length === 0) {
      return '// Error: No Output node found. Add at least one Output node.';
    }

    const secretNodes = nodes.filter((n) => n.type === 'secretNode');
    const envVars = secretNodes
      .map((s) => `// ${s.data.secretKey}: Set in your .env file`)
      .join('\n');

    const tools = inputNodes.map((inputNode) => {
      const reachable = this.getReachableNodes(inputNode.id, nodes, edges);
      return this.generateTool(inputNode, reachable, edges);
    });

    return `import { MCPServer, text, object, widget, error } from "mcp-use/server";
import { z } from "zod";

${envVars ? `${envVars}\n` : ''}
const server = new MCPServer({
  name: "mcp-flow-server",
  version: "1.0.0",
  description: "Generated by MCP-Flow",
});

${tools.join('\n\n')}

server.listen().then(() => console.log("MCP server running"));
`;
  }

  validate(graph: Graph): { valid: boolean; errors: string[] } {
    const { nodes, edges } = graph;
    const errors: string[] = [];

    const inputNodes = nodes.filter((n) => n.type === 'inputNode');
    const outputNodes = nodes.filter((n) => n.type === 'outputNode');

    if (inputNodes.length === 0) errors.push('No Input node found');
    if (outputNodes.length === 0) errors.push('No Output node found');

    inputNodes.forEach((input) => {
      if (!input.data.name)
        errors.push(`Input node ${input.id} has no tool name`);
      const reachable = this.getReachableNodes(input.id, nodes, edges);
      const hasOutput = reachable.some((n) => n.type === 'outputNode');
      if (!hasOutput)
        errors.push(
          `Input "${input.data.name || input.id}" has no path to an Output node`,
        );
    });

    nodes
      .filter((n) => n.type === 'httpNode')
      .forEach((http) => {
        if (!http.data.url)
          errors.push(`HTTP node ${http.id} has no URL configured`);
      });

    const connectedNodeIds = new Set<string>();
    edges.forEach((e) => {
      connectedNodeIds.add(e.source);
      connectedNodeIds.add(e.target);
    });
    nodes.forEach((n) => {
      if (!connectedNodeIds.has(n.id) && nodes.length > 1) {
        errors.push(`Node "${n.type}" (${n.id.slice(0, 10)}) is disconnected`);
      }
    });

    return { valid: errors.length === 0, errors };
  }

  private getReachableNodes(
    startId: string,
    nodes: GraphNode[],
    edges: GraphEdge[],
  ): GraphNode[] {
    const visited = new Set<string>();
    const queue = [startId];
    const result: GraphNode[] = [];

    while (queue.length > 0) {
      const current = queue.shift()!;
      if (visited.has(current)) continue;
      visited.add(current);

      const node = nodes.find((n) => n.id === current);
      if (node && node.id !== startId) result.push(node);

      edges
        .filter((e) => e.source === current)
        .forEach((e) => {
          if (!visited.has(e.target)) queue.push(e.target);
        });
    }

    return result;
  }

  private topologicalSort(
    startId: string,
    nodes: GraphNode[],
    edges: GraphEdge[],
  ): GraphNode[] {
    const adj = new Map<string, string[]>();
    const inDegree = new Map<string, number>();

    const reachableIds = new Set<string>([startId]);
    const queue = [startId];
    while (queue.length > 0) {
      const curr = queue.shift()!;
      edges
        .filter((e) => e.source === curr)
        .forEach((e) => {
          if (!reachableIds.has(e.target)) {
            reachableIds.add(e.target);
            queue.push(e.target);
          }
        });
    }

    for (const id of reachableIds) {
      adj.set(id, []);
      inDegree.set(id, 0);
    }

    for (const edge of edges) {
      if (reachableIds.has(edge.source) && reachableIds.has(edge.target)) {
        adj.get(edge.source)!.push(edge.target);
        inDegree.set(edge.target, (inDegree.get(edge.target) || 0) + 1);
      }
    }

    const sorted: string[] = [];
    const q: string[] = [];
    for (const [id, deg] of inDegree.entries()) {
      if (deg === 0) q.push(id);
    }

    while (q.length > 0) {
      const curr = q.shift()!;
      sorted.push(curr);
      for (const neighbor of adj.get(curr) || []) {
        inDegree.set(neighbor, inDegree.get(neighbor)! - 1);
        if (inDegree.get(neighbor) === 0) q.push(neighbor);
      }
    }

    return sorted
      .filter((id) => id !== startId)
      .map((id) => nodes.find((n) => n.id === id)!)
      .filter(Boolean);
  }

  private generateTool(
    inputNode: GraphNode,
    reachable: GraphNode[],
    edges: GraphEdge[],
  ): string {
    const toolName = inputNode.data.name || 'my_tool';
    const toolDescription = inputNode.data.description || 'Generated tool';
    const parameters = inputNode.data.parameters || [];
    const outputNode = reachable.find((n) => n.type === 'outputNode');
    const isWidget = outputNode?.data.outputType === 'widget';

    const zodFields = parameters
      .map((p: NodeParameter) => {
        let zodType = 'z.string()';
        if (p.type === 'number') zodType = 'z.number()';
        if (p.type === 'boolean') zodType = 'z.boolean()';
        if (p.defaultValue)
          zodType += `.default(${JSON.stringify(p.defaultValue)})`;
        if (p.required === false) zodType += '.optional()';
        if (p.description) zodType += `.describe("${p.description}")`;
        return `      ${p.name}: ${zodType},`;
      })
      .join('\n');

    const sorted = this.topologicalSort(
      inputNode.id,
      [inputNode, ...reachable],
      edges,
    );
    const bodyLines = this.generateNodeChain(sorted);

    return `server.tool(
  {
    name: "${toolName}",
    description: "${toolDescription}",
    schema: z.object({
${zodFields}
    }),${
      isWidget
        ? `
    widget: {
      name: "${toolName}-widget",
      invoking: "${outputNode?.data.widgetDescription || 'Processing...'}",
      invoked: "${outputNode?.data.widgetTitle || 'Completed'}",
    },`
        : ''
    }
  },
  async (params) => {
    try {
      let data: Record<string, unknown> = { ...params };
${bodyLines}
    } catch (err: unknown) {
      return error(\`Tool execution failed: \${err instanceof Error ? err.message : String(err)}\`);
    }
  }
);`;
  }

  private generateNodeChain(nodes: GraphNode[]): string {
    const lines: string[] = [];

    for (const node of nodes) {
      switch (node.type) {
        case 'httpNode':
          lines.push(this.generateHttpCode(node));
          break;
        case 'transformNode':
          lines.push(this.generateTransformCode(node));
          break;
        case 'conditionNode':
          lines.push(this.generateConditionCode(node));
          break;
        case 'secretNode':
          lines.push(this.generateSecretCode(node));
          break;
        case 'outputNode':
          lines.push(this.generateOutputCode(node));
          break;
      }
    }

    return lines.map((l) => '      ' + l).join('\n\n');
  }

  private generateHttpCode(node: GraphNode): string {
    const { method = 'GET', url = '', headers = {}, body = '' } = node.data;
    const processedUrl = this.templateStr(url);

    const headerEntries = Object.entries(headers)
      .map(([k, v]) => `        "${k}": ${this.templateStr(String(v))},`)
      .join('\n');

    let fetchOptions = `{
        method: "${method}",
        headers: {
          "Content-Type": "application/json",
${headerEntries}
        },`;

    if (method !== 'GET' && body) {
      fetchOptions += `\n        body: JSON.stringify(${this.templateStr(body)}),`;
    }

    fetchOptions += '\n      }';

    return `// HTTP Request: ${method} ${url || 'no-url'}
const response_${node.id.replace(/[^a-zA-Z0-9]/g, '_')} = await fetch(\`${processedUrl}\`, ${fetchOptions});
if (!response_${node.id.replace(/[^a-zA-Z0-9]/g, '_')}.ok) {
  return error(\`HTTP \${response_${node.id.replace(/[^a-zA-Z0-9]/g, '_')}.status}: \${response_${node.id.replace(/[^a-zA-Z0-9]/g, '_')}.statusText}\`);
}
data = await response_${node.id.replace(/[^a-zA-Z0-9]/g, '_')}.json();`;
  }

  private generateTransformCode(node: GraphNode): string {
    const { mappings = [], expression = '' } = node.data;
    const lines: string[] = ['// Transform'];

    if (mappings.length > 0) {
      lines.push('const mapped: Record<string, unknown> = {};');
      mappings.forEach((m: TransformMapping) => {
        if (m.from && m.to) {
          lines.push(
            `mapped[${JSON.stringify(m.to)}] = data${m.from
              .split('.')
              .map((p: string) => `[${JSON.stringify(p)}]`)
              .join('')};`,
          );
        }
      });
      lines.push('data = { ...data, ...mapped };');
    }

    if (expression) {
      lines.push(`data = (() => { ${expression} })(data) ?? data;`);
    }

    return lines.join('\n');
  }

  private generateConditionCode(node: GraphNode): string {
    const { field = '', operator = 'equals', value = '' } = node.data;

    const fieldAccess = `data${field
      .split('.')
      .map((p: string) => `[${JSON.stringify(p)}]`)
      .join('')}`;
    let condition = '';

    switch (operator) {
      case 'equals':
        condition = `${fieldAccess} === ${JSON.stringify(value)}`;
        break;
      case 'not_equals':
        condition = `${fieldAccess} !== ${JSON.stringify(value)}`;
        break;
      case 'contains':
        condition = `String(${fieldAccess}).includes(${JSON.stringify(value)})`;
        break;
      case 'gt':
        condition = `Number(${fieldAccess}) > ${Number(value)}`;
        break;
      case 'lt':
        condition = `Number(${fieldAccess}) < ${Number(value)}`;
        break;
      case 'gte':
        condition = `Number(${fieldAccess}) >= ${Number(value)}`;
        break;
      case 'lte':
        condition = `Number(${fieldAccess}) <= ${Number(value)}`;
        break;
      case 'exists':
        condition = `${fieldAccess} !== undefined && ${fieldAccess} !== null`;
        break;
      case 'not_exists':
        condition = `${fieldAccess} === undefined || ${fieldAccess} === null`;
        break;
      default:
        condition = 'true';
    }

    return `// Condition: ${field} ${operator} ${value}
if (${condition}) {
  // true branch
} else {
  // false branch
}`;
  }

  private generateSecretCode(node: GraphNode): string {
    const key = node.data.secretKey || 'UNNAMED';
    return `// Secret: ${key}
const secret_${key} = process.env["${key}"];
if (!secret_${key}) {
  return error("Missing environment variable: ${key}");
}`;
  }

  private generateOutputCode(node: GraphNode): string {
    if (node.data.outputType === 'widget') {
      const title = node.data.widgetTitle || 'Result';
      const desc = node.data.widgetDescription || '';
      return `// Output: Interactive Widget
return widget({
  props: { data },
  output: text("${title}${desc ? ': ' + desc : ''}"),
  message: "${title}",
});`;
    }
    return `// Output: JSON
return object(data);`;
  }

  private templateStr(str: string): string {
    return str
      .replace(/\{\{input\.(.*?)\}\}/g, '${params.$1}')
      .replace(/\{\{secret\.(.*?)\}\}/g, '${process.env["$1"]}')
      .replace(/\{\{(.*?)\}\}/g, '${data.$1}');
  }
}
